FROM --platform=linux/amd64 ubuntu:24.04 AS builder

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libembree-dev libtbb-dev groff cmake build-essential git

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8

FROM ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libtbb12 libembree4-4
COPY --from=builder /repo/build/bspinfo/bspinfo /
